2025-03-13 09:49:59,754 ERROR: Exception on /user/Gerardo Salvador [GET] [in C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\app\routes.py", line 103, in user
    return render_template("user.html", user=user, posts=posts, form=form, current_user_id = current_user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\flaskmegatutorial\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\flaskmegatutorial\app\templates\base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\app\templates\user.html", line 37, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\app\templates\_post.html", line 12, in top-level template code
    says: {{ moment(post.timestamp).fromNow() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_moment\__init__.py", line 237, in fromNow
    return self._render("fromNow", no_suffix=int(no_suffix),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_moment\__init__.py", line 194, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_moment\__init__.py", line 190, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
           ^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'timestamp'
2025-03-13 09:51:13,625 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:58]
2025-03-13 10:01:03,639 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:58]
2025-03-13 10:01:05,777 ERROR: Exception on /user/Gerardo Salvador [GET] [in C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\app\routes.py", line 99, in user
    current_user.posts(),
    ^^^^^^^^^^^^^^^^^^^^
TypeError: 'WriteOnlyCollection' object is not callable
2025-03-13 10:02:14,599 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:58]
2025-03-13 10:02:16,421 ERROR: Exception on /user/Gerardo Salvador [GET] [in C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\app\routes.py", line 98, in user
    posts = db.paginate(
            ^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_sqlalchemy\extension.py", line 839, in paginate
    return SelectPagination(
           ^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 72, in __init__
    items = self._query_items()
            ^^^^^^^^^^^^^^^^^^^
  File "C:\flaskmegatutorial\.venv\Lib\site-packages\flask_sqlalchemy\pagination.py", line 337, in _query_items
    select = select.limit(self.per_page).offset(self._query_offset)
             ^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'limit'
2025-03-13 10:09:55,256 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:58]
2025-03-13 10:10:31,520 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:58]
2025-03-13 12:09:58,667 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:63]
2025-03-13 12:12:37,295 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:64]
2025-03-13 12:18:44,349 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:64]
2025-03-13 12:35:11,482 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:64]
2025-03-13 12:36:24,930 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:64]
2025-03-13 12:38:46,002 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:64]
2025-03-13 12:44:43,051 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 12:56:57,716 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:05:07,595 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:19:28,171 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:20:43,413 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:23:05,628 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:23:47,682 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:27:25,412 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:27:47,400 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
2025-03-13 13:28:57,435 INFO: Microblog startup [in C:\flaskmegatutorial\app\__init__.py:67]
